name: Engineering Task
description: New Engineering Task (For Internal Microsoft Use Only).
labels: ["untriaged", "internal"]
body:     
- type: markdown
  attributes:
    value: |
      ## Engineering Task **(For Internal Use Only)**
      
- type: dropdown
  attributes:
    label: Type of task?
    description: Can you select a category for this task?
    multiple: true
    options: 
      - "Design"
      - "Test"
      - "Evaluation"
      - "Prototype"
      - "Builds"
      - "Development"
      - "Best Practices"
      - "Supportability"
      - "Engineering Excellence"
      - "Performance"
      - "Security"
      - "Other(s)"
  validations:
    required: true

- type: textarea
  attributes:
    label: Description
    description: "Please describe briefly what this task is about."
  validations: 
    required: true

- type: textarea
  attributes:
    label: Solution
    description: "Describe the solution you'd like."
  validations: 
    required: false
